package org.olcbox.app.net

import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.addJsonObject
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.put
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * JVM-only: runs the real parser+builder on realistic share links and writes the
 * generated sing-box configs to `build/singbox-configs/`. The singbox-verify CI
 * workflow then runs `sing-box check` on each against the pinned binary — proving
 * the config schema matches the real sing-box release, not just valid JSON.
 */
class SingBoxConfigDumpTest {
    private val outDir = File("build/singbox-configs")

    private fun dump(name: String, json: String) {
        outDir.mkdirs()
        File(outDir, "$name.json").writeText(json)
        val reference = File("src/jvmTest/resources/reference-configs/$name.json")
        if (reference.isFile) {
            val expected = Json.parseToJsonElement(reference.readText())
            val actual = normalizedReference(Json.parseToJsonElement(json))
            assertEquals(expected.toString(), actual.toString(),
                "$name changed from the config generated by main before this PR")
        }
    }

    /** Build directories differ across checkouts; only local rule paths are normalized. */
    private fun normalizedReference(value: JsonElement): JsonElement = when (value) {
        is JsonObject -> JsonObject(value.mapValues { (key, child) ->
            if (key == "path" && child is JsonPrimitive && child.content.endsWith(".srs")) {
                JsonPrimitive("@rules/" + child.content.replace('\\', '/').substringAfterLast('/'))
            } else {
                normalizedReference(child)
            }
        })
        is JsonArray -> JsonArray(value.map(::normalizedReference))
        else -> value
    }

    // The protocols a provider's subscription may carry besides VLESS and Hysteria2.
    // No reference file: these shapes are new, and CI's `sing-box check` is the test.
    @Test fun dumpTrojanWs() {
        val spec = LinkParser.parse(
            "trojan://secret@127.0.0.1:443?security=tls&sni=example.com&type=ws&path=%2Fws&host=cdn.example.com&fp=chrome&alpn=h2%2Chttp%2F1.1#T"
        )
        assertNotNull(spec)
        dump("trojan-ws", SingBoxConfig.build(spec))
    }

    @Test fun dumpShadowsocksAead() {
        val spec = LinkParser.parse("ss://YWVzLTI1Ni1nY206c2VjcmV0@127.0.0.1:8388#SS")
        assertNotNull(spec)
        dump("shadowsocks-aead", SingBoxConfig.build(spec))
    }

    @Test fun dumpShadowsocks2022() {
        val spec = LinkParser.parse(
            "ss://2022-blake3-aes-256-gcm:AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8%3D@127.0.0.1:8388#SS2022"
        )
        assertNotNull(spec)
        dump("shadowsocks-2022", SingBoxConfig.build(spec))
    }

    @Test fun dumpVmessWsTls() {
        val json = """{"v":"2","ps":"VM","add":"127.0.0.1","port":"443","id":"11111111-1111-1111-1111-111111111111",""" +
            """"aid":"0","scy":"auto","net":"ws","host":"cdn.example.com","path":"/vm","tls":"tls","sni":"cdn.example.com","fp":"chrome"}"""
        val spec = LinkParser.parse("vmess://" + java.util.Base64.getEncoder().encodeToString(json.toByteArray()))
        assertNotNull(spec)
        dump("vmess-ws-tls", SingBoxConfig.build(spec))
    }

    @Test fun dumpVlessWsTls() {
        val spec = LinkParser.parse(
            "vless://11111111-1111-1111-1111-111111111111@127.0.0.1:443?security=tls&sni=example.com&type=ws&path=%2Fv&host=cdn.example.com&fp=chrome#V"
        )
        assertNotNull(spec)
        dump("vless-ws-tls", SingBoxConfig.build(spec))
    }

    @Test fun dumpVlessRealityTcp() {
        val link = "vless://11111111-1111-1111-1111-111111111111@127.0.0.1:443" +
            "?security=reality&encryption=none&pbk=jNXHt1yRo0vDuchQlIP6Z0ZvjT3KtzVI-T4E7RoLJS0" +
            "&sid=ab12cd34&fp=chrome&sni=www.microsoft.com&flow=xtls-rprx-vision&type=tcp#DE-reality"
        val spec = LinkParser.parse(link)
        assertNotNull(spec)
        dump("vless-reality", SingBoxConfig.build(spec))
    }

    @Test fun dumpVlessGrpcReality() {
        val link = "vless://11111111-1111-1111-1111-111111111111@127.0.0.1:2053" +
            "?security=reality&pbk=jNXHt1yRo0vDuchQlIP6Z0ZvjT3KtzVI-T4E7RoLJS0" +
            "&sni=rutube.ru&type=grpc&serviceName=media%2Fsync#KZ-grpc"
        val spec = LinkParser.parse(link)
        assertNotNull(spec)
        dump("grpc-reality", SingBoxConfig.build(spec))
    }

    // xhttp is NOT a sing-box transport — it's handled by Xray-core (see
    // XrayConfigDumpTest). sing-box covers reality (tcp) + hy2 + olcrtc-socks.

    @Test fun dumpHysteria2() {
        val link = "hysteria2://PASSWORD123@127.0.0.1:443?sni=www.microsoft.com&obfs=salamander&obfs-password=OBFSPW&insecure=1#RU-hy2"
        val spec = LinkParser.parse(link)
        assertNotNull(spec)
        dump("hysteria2", SingBoxConfig.build(spec))
    }

    @Test fun dumpOlcrtcSocks() {
        dump("olcrtc-socks", SingBoxConfig.buildOlcrtcSocks(olcrtcPort = 10808))
        assertTrue(File(outDir, "olcrtc-socks.json").exists())
    }

    /**
     * The shape the macOS root daemon runs. Everything unique to it — the route
     * exclusion, the direct-DNS rule, the second inbound — is schema the other
     * dumps never exercise, and all of it is 1.12+ syntax.
     */
    @Test fun dumpDesktopTun() {
        dumpWithSocksTwin(
            "desktop-tun",
            SingBoxConfig.buildDesktopTun(
                corePort = 10810,
                verifyPort = 10811,
                excludeAddresses = listOf("203.0.113.7/32"),
                directDnsDomains = listOf("de1.example.org"),
                upstreamUdpIsLossy = true,
                cacheFilePath = "/Library/Application Support/org.olcbox.app/cache.db"
            )
        )
        assertTrue(File(outDir, "desktop-tun.json").exists())
    }

    /** The daemon's shape under Bypass Russia: rule-sets, a bound direct outbound, fake addresses. */
    @Test fun dumpDesktopTunBypass() = runTest {
        val rules = File(outDir, "rules").apply { mkdirs() }
        for (file in RuleSets.all) File(rules, file.name).writeBytes(RuleSets.bytes(file))
        dumpWithSocksTwin(
            "desktop-tun-bypass",
            SingBoxConfig.buildDesktopTun(
                corePort = 10810,
                verifyPort = 10811,
                excludeAddresses = listOf("203.0.113.7/32"),
                directDnsDomains = listOf("de1.example.org"),
                routing = Routing.BypassRussia(rules.absolutePath, DirectDns.System),
                bindInterface = "en0",
                cacheFilePath = "/Library/Application Support/org.olcbox.app/cache.db"
            )
        )
        assertTrue(File(outDir, "desktop-tun-bypass-as-socks.json").exists())
    }

    /**
     * The same builder without olcRTC's lossy-carrier handling — no hijack rule,
     * no remote resolver. It is a different config, so it gets its own check: the
     * first version of this shape was rejected by sing-box in exactly the section
     * the two variants differ in.
     */
    @Test fun dumpDesktopTunNative() {
        dump(
            "desktop-tun-native",
            SingBoxConfig.buildDesktopTun(
                corePort = 10810,
                verifyPort = 10811,
                excludeAddresses = listOf("203.0.113.7/32", "2001:db8::1/128"),
                directDnsDomains = listOf("de1.example.org")
            )
        )
        assertTrue(File(outDir, "desktop-tun-native.json").exists())
    }

    /** The exact Windows shape: named Wintun, carrier bypass, bound direct, and authenticated probe. */
    @Test fun dumpDesktopTunWindows() {
        dumpWithSocksTwin(
            "desktop-tun-windows",
            SingBoxConfig.buildDesktopTun(
                corePort = 10810,
                verifyPort = 10811,
                verifyUsername = "random-probe-user",
                verifyPassword = "random-probe-password",
                username = "upstream-user",
                password = "upstream-password",
                excludeAddresses = listOf("203.0.113.7/32"),
                directDnsDomains = listOf("edge.example.org"),
                bindInterface = "Ethernet",
                bypassProcessPaths = listOf(
                    "C:\\Program Files\\Ghostlane\\sing-box.exe",
                    "C:\\Program Files\\Ghostlane\\xray.exe"
                ),
                interfaceName = "Ghostlane-a1b2c3d4-1-0"
            )
        )
        assertTrue(File(outDir, "desktop-tun-windows.json").exists())
    }
    /**
     * Bypass Russia. Every rule-set is a real file here, because `sing-box check`
     * opens local rule-sets while building the router — a missing file fails the
     * check exactly as it would fail a connect.
     */
    /**
     * A tun shape cannot be started on a runner — a tun needs privileges — but
     * everything that failed at *start* so far lived in the dns section, which
     * a socks inbound exercises just as well. So every tun dump also gets a
     * twin with a socks inbound and its cache file pointed into the build
     * directory, and the check script starts the twin.
     */
    private fun dumpWithSocksTwin(name: String, json: String) {
        dump(name, json)
        val obj = Json.parseToJsonElement(json).jsonObject.toMutableMap()
        obj["inbounds"] = buildJsonArray {
            addJsonObject {
                put("type", "socks"); put("tag", "in")
                put("listen", "127.0.0.1"); put("listen_port", 18811)
            }
        }
        val experimental = obj["experimental"]?.jsonObject?.toMutableMap() ?: mutableMapOf()
        val cache = experimental["cache_file"]?.jsonObject?.toMutableMap() ?: mutableMapOf()
        cache["path"] = JsonPrimitive(File(outDir, "$name.cache.db").absolutePath)
        experimental["cache_file"] = JsonObject(cache)
        obj["experimental"] = JsonObject(experimental)
        // A daemon shape binds its direct outbound to a macOS interface; the twin
        // runs on Linux, so it binds to the loopback there — nothing dials.
        obj["outbounds"] = buildJsonArray {
            obj["outbounds"]!!.jsonArray.forEach { outbound ->
                val fields = outbound.jsonObject.toMutableMap()
                if (fields["bind_interface"] != null) fields["bind_interface"] = JsonPrimitive("lo")
                add(JsonObject(fields))
            }
        }
        dump("$name-as-socks", JsonObject(obj).toString())
    }

    /** The iOS shapes in Global: they answer DNS themselves now, with fake addresses. */
    @Test fun dumpIosShapes() {
        val reality = LinkParser.parse(
            "vless://11111111-1111-1111-1111-111111111111@127.0.0.1:443" +
                "?security=reality&encryption=none&pbk=jNXHt1yRo0vDuchQlIP6Z0ZvjT3KtzVI-T4E7RoLJS0" +
                "&sid=ab12cd34&fp=chrome&sni=www.microsoft.com&flow=xtls-rprx-vision&type=tcp#DE-reality"
        )
        assertNotNull(reality)
        dumpWithSocksTwin("ios-tun-reality", SingBoxConfig.buildTun(reality))
        dumpWithSocksTwin(
            "ios-tun-reality-debug",
            SingBoxConfig.buildTun(reality, verboseLogs = true, logOutput = "sing-box.log")
        )
        dumpWithSocksTwin(
            "ios-tun-socks-lossy",
            SingBoxConfig.buildTunSocks(10810, username = "u", password = "p", upstreamUdpIsLossy = true)
        )
        assertTrue(File(outDir, "ios-tun-socks-lossy-as-socks.json").exists())
    }

    @Test fun dumpBypassShapes() = runTest {
        val rules = File(outDir, "rules").apply { mkdirs() }
        for (file in RuleSets.all) File(rules, file.name).writeBytes(RuleSets.bytes(file))
        val android = Routing.BypassRussia(rules.absolutePath, DirectDns.Servers(listOf("10.20.30.40")))
        val ios = Routing.BypassRussia(rules.absolutePath, DirectDns.Placeholder)

        val reality = LinkParser.parse(
            "vless://11111111-1111-1111-1111-111111111111@127.0.0.1:443" +
                "?security=reality&encryption=none&pbk=jNXHt1yRo0vDuchQlIP6Z0ZvjT3KtzVI-T4E7RoLJS0" +
                "&sid=ab12cd34&fp=chrome&sni=www.microsoft.com&flow=xtls-rprx-vision&type=tcp#DE-reality"
        )
        assertNotNull(reality)
        val hy2 = LinkParser.parse(
            "hysteria2://PASSWORD123@127.0.0.1:443?sni=www.microsoft.com&obfs=salamander&obfs-password=OBFSPW&insecure=1#RU-hy2"
        )
        assertNotNull(hy2)

        dump("bypass-socks-reality", SingBoxConfig.build(reality, routing = android))
        dump("bypass-socks-chain", SingBoxConfig.buildSocksChain(10808, username = "u", password = "p", routing = android))
        dumpWithSocksTwin("bypass-tun-reality", SingBoxConfig.buildTun(reality, routing = ios))
        dumpWithSocksTwin("bypass-tun-hysteria2", SingBoxConfig.buildTun(hy2, routing = ios))
        dumpWithSocksTwin("bypass-tun-socks", SingBoxConfig.buildTunSocks(10810, routing = ios))
        dumpWithSocksTwin(
            "bypass-tun-socks-lossy",
            SingBoxConfig.buildTunSocks(10810, username = "u", password = "p", upstreamUdpIsLossy = true, routing = ios)
        )
        assertTrue(File(outDir, "bypass-tun-socks-lossy.json").exists())
    }

    @Test fun dumpIranAndChinaAndroidFrontsAndDesktopTun() = runTest {
        val rules = File(outDir, "rules").apply { mkdirs() }
        for (file in RuleSets.bundled) File(rules, file.name).writeBytes(RuleSets.bytes(file))
        val spec = LinkParser.parse(
            "vless://11111111-1111-1111-1111-111111111111@127.0.0.1:443" +
                "?security=reality&encryption=none&pbk=jNXHt1yRo0vDuchQlIP6Z0ZvjT3KtzVI-T4E7RoLJS0" +
                "&sid=ab12cd34&fp=chrome&sni=www.microsoft.com&type=tcp#regional"
        )
        assertNotNull(spec)
        for (region in listOf("ir", "cn")) {
            val routing = Routing.Rules(rules.absolutePath, DirectDns.System, region)
            dump("regional-$region-socks", SingBoxConfig.build(spec, routing = routing))
            dump("regional-$region-front", SingBoxConfig.buildSocksChain(10808, routing = routing))
            dumpWithSocksTwin(
                "regional-$region-desktop-tun",
                SingBoxConfig.buildDesktopTun(
                    corePort = 10810,
                    verifyPort = 10811,
                    routing = routing,
                    bindInterface = "en0"
                )
            )
        }
    }
}
